### ISSUE TITLE
Rename the branch where changes are being performed

### ISSUE THREAD

**Issue by Cristrinaranjus** [CCOMS-UAM/yos-award#2]
I noticed that the branch where the changes are being made is called "feture" instead of "feature". It could be interesting to rename it to correct that typo.

**Comment by DaniMori** [comment]
Thanks for bringing this up @Cristrinaranjus! Sorry for the mistake... not really sure if it's worth changing it, the solution may be a little headache :S

**Comment by Cristrinaranjus** [comment]
Ok. As it is now merged, not a problem anymore!

**Comment by DaniMori** [comment]
I'll label it as "rejected" ;)

(Also, I changed its state to "close as not planned" instead of "close as complete")
